name: Build, Test, and Deploy ASP.NET Application

# Trigger the workflow on push, pull request events to the main branch, and manual invocation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual invocation of the workflow

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Check out the repository code

    - name: Setup .NET
      uses: actions/setup-dotnet@v2 # Set up the .NET environment
      with:
        dotnet-version: '8.x' # Specify the .NET version to use

    - name: Restore dependencies
      run: dotnet restore # Restore the project dependencies

    - name: Build
      run: dotnet build --configuration Release --no-restore # Build the project in Release configuration

    - name: Test
      run: dotnet test --no-restore --verbosity normal # Run the tests with normal verbosity

    - name: Publish build artifacts
      run: dotnet publish -c Release -o ./publish # Publish the build artifacts to the ./publish directory

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2 # Upload the build artifacts
      with:
        name: aspnet-app
        path: ./publish

  deploy_infrastructure:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Check out the repository code

    - name: Azure Login
      uses: azure/login@v1 # Log in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep template
      run: |
        az deployment group create \
          --resource-group Demo69888 \
          --template-file ./bicep/template.bicep \
          --parameters @./bicep/parameters-prod.json

  deploy_webapp:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    needs: [build, deploy_infrastructure] # Ensure this job runs after build and deploy_infrastructure jobs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Check out the repository code

    - name: Azure Login
      uses: azure/login@v1 # Log in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download build artifacts
      uses: actions/download-artifact@v2 # Download the build artifacts
      with:
        name: aspnet-app
        path: .

    - name: Deploy to Web App
      run: |
        az webapp deploy \
          --resource-group demo69888 \
          --name demo69888 \
          --src-path .
